Podfile.lock
StreamChatIntegration.xcworkspace/xcshareddata/swiftpm/Package.resolved

Release 4.5.1

---

.github/workflows/pull-request.yml
Podfile.lock
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration.xcworkspace/xcshareddata/swiftpm/Package.resolved
fastlane/Fastfile

Release 4.6.0

---

Podfile.lock
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Podfile.lock

Release 4.7.0

---

Cartfile.resolved
Podfile.lock
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile.lock
XCIntegration/fastlane/report.xml
fastlane/README.md

4.9.0 Release

---

Cartfile.resolved
Podfile.lock
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/fastlane/report.xml

4.11.0 Release

---

Cartfile.resolved
Podfile.lock
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
XCIntegration/Cartfile.resolved
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/fastlane/report.xml

4.12.0 Release

---

Cartfile.resolved
Podfile.lock
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/fastlane/report.xml

4.13.0 Release

---

.github/workflows/pull-request.yml
Cartfile.resolved
Podfile.lock
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/fastlane/report.xml
fastlane/Fastfile

4.14.0 Release

---

Cartfile.resolved
Podfile.lock
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/fastlane/report.xml

4.16.0 Release

---

Cartfile.resolved
Podfile.lock
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved
fastlane/Fastfile

4.18.0 Release

---

Cartfile.resolved
Podfile.lock
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved

4.19.0 Release

---

Cartfile.resolved
Podfile.lock
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved

4.20.0 Release

---

Cartfile.resolved
Podfile.lock
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegrationSource/StreamChat/StreamChatWrapper.swift
XCIntegration/Cartfile.resolved
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved
fastlane/Fastfile

4.21.0 Release

---

Cartfile.resolved
Podfile.lock
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved

4.22.0 Release

---

Cartfile.resolved
Podfile.lock
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved

4.24.0 Release

---

Cartfile.resolved
Podfile.lock
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved

4.24.1 Release

---

Cartfile.resolved
Podfile.lock
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved

4.25.0 Release

---

Cartfile.resolved
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved

4.25.1 Release

---

Cartfile.resolved
Podfile.lock
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved

4.26.0 Release

---

Cartfile.resolved
Podfile.lock
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved

4.27.0 Release

---

Cartfile.resolved
Podfile.lock
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved

4.27.1 Release

---

Cartfile.resolved
Podfile.lock
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved

4.28.0 Release

---

Cartfile.resolved
Podfile.lock
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved

4.29.0 Release

---

Cartfile.resolved
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved

4.30.0 Release

---

Cartfile.resolved
Podfile.lock
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved

4.31.0 Release

---

Cartfile
Podfile
Podfile.lock
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Podfile
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved

4.32.0 Release

---

Cartfile
Cartfile.resolved
Podfile
Podfile.lock
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved
fastlane/Fastfile

4.33.0 Release

---

fastlane/Fastfile

Fix the edge case in the release lane when all config files are cleared if the previous release tag is not found

Fix the edge case in release lane

---

Cartfile
Cartfile.resolved
Podfile
Podfile.lock
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved

4.34.0 Release

---

Cartfile
Cartfile.resolved
Podfile
Podfile.lock
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved

4.35.0 Release

---

Cartfile
Cartfile.resolved
Podfile
Podfile.lock
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved

4.35.1 Release

---

Cartfile
Cartfile.resolved
Podfile
Podfile.lock
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved

4.35.2 Release

---

Cartfile
Cartfile.resolved
Podfile
Podfile.lock
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved

4.36.0 Release

---

Cartfile
Cartfile.resolved
Podfile
Podfile.lock
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Podfile
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved

Release 4.37.0

---

Cartfile
Cartfile.resolved
Podfile
Podfile.lock
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved

4.37.1 Release

---

Cartfile
Cartfile.resolved
Podfile
Podfile.lock
StreamChatIntegration-Carthage.xcodeproj/project.pbxproj
StreamChatIntegration-CocoaPods.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-MultiBundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
StreamChatIntegration.xcworkspace/xcshareddata/swiftpm/Package.resolved
XCIntegration/Cartfile.resolved
XCIntegration/Podfile
XCIntegration/Podfile.lock
XCIntegration/StreamChatIntegration-XC-Carthage.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC-CocoaPods.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj
XCIntegration/StreamChatIntegration-XC.xcworkspace/xcshareddata/swiftpm/Package.resolved

4.38.0 Release

---

Cartfile
Podfile
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
XCIntegration/Podfile
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj

4.39.0 Release

---

Cartfile
Podfile
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
XCIntegration/Podfile
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj

4.40.0 Release

---

Cartfile
Podfile
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
XCIntegration/Podfile
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj

4.41.0 Release

---

Cartfile
Podfile
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
XCIntegration/Podfile
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj

4.42.0 Release

---

Cartfile
Podfile
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
XCIntegration/Podfile
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj

4.43.0 Release

---

Cartfile
Podfile
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
XCIntegration/Podfile
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj

4.44.0 Release

---

Cartfile
Podfile
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
XCIntegration/Podfile
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj

4.46.0 Release

---

Cartfile
Podfile
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
XCIntegration/Podfile
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj

4.47.0 Release

---

Cartfile
Podfile
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
XCIntegration/Podfile
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj

4.47.1 Release

---

Cartfile
Podfile
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
XCIntegration/Podfile
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj

4.48.0 Release

---

Cartfile
Podfile
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
XCIntegration/Podfile
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj

4.48.1 Release

---

Cartfile
Podfile
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
XCIntegration/Podfile
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj

4.49.0 Release

---

Cartfile
Podfile
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
XCIntegration/Podfile
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj

4.50.0 Release

---

Cartfile
Podfile
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
XCIntegration/Podfile
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj

4.51.0 Release

---

Cartfile
Podfile
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
XCIntegration/Podfile
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj

4.53.0 Release

---

Cartfile
Podfile
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
XCIntegration/Podfile
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj

4.54.0 Release

---

Cartfile
Podfile
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
XCIntegration/Podfile
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj

4.55.0 Release

---

Cartfile
Podfile
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
XCIntegration/Podfile
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj

4.56.0 Release

---

Cartfile
Podfile
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
XCIntegration/Podfile
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj

4.56.1 Release

---

Cartfile
Podfile
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
XCIntegration/Podfile
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj

4.57.0 Release

---

Cartfile
Podfile
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
XCIntegration/Podfile
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj

4.58.0 Release

---

Cartfile
Podfile
StreamChatIntegration-MultiBundle.xcodeproj/project.pbxproj
StreamChatIntegration-SPM.xcodeproj/project.pbxproj
XCIntegration/Podfile
XCIntegration/StreamChatIntegration-XC-SPM.xcodeproj/project.pbxproj

4.59.0 Release
